<center>
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DS0105EN-SkillsNetwork/labs/Module2/images/SN_web_lightmode.png" width="300" alt="cognitiveclass.ai logo">
</center>

#### Add your code below following the instructions given in the course

**TOOLS FOR DATA SCIENCE**

This is a jupyter notebook for peer-graded assignment in the course "Tools for Data Science"

There're many Data Science languages, including but not limited to
1. Python
2. R
3. SQL
4. Scala
5. Java
6. C++
7. Julia
8. JavaScript
9. PHP
10. Go
11. Ruby
12. Visual Basic

Supporting data science libraries include:
1. Pandas
2. Numpy
3. Matplotlib
4. Seaborn
5. Scikit-learn
6. Keras
7. TensorFlow
8. PyTorch
9. Apache Spark
10. Vegas
11. BigDL
12. Ggplot2

# Data Science Tools

| Data Science Tools            |
|---------------------|
| Anaconda     |
| Jupyter Notebook |
| RStudito |
| Spyder |
| Zeppelin        |

# Arithmetic Expressions Examples

Arithmetic expressions are mathematical statements that perform basic arithmetic operations. These include addition, subtraction, multiplication, division, and exponentiation. Below are some examples of arithmetic expressions:

1. **Addition (+)**: This operation adds two numbers together.
   - Example: `3 + 5 = 8`

2. **Subtraction (-)**: This operation subtracts one number from another.
   - Example: `10 - 4 = 6`

3. **Multiplication (*)**: This operation multiplies two numbers.
   - Example: `7 * 3 = 21`

4. **Division (/)**: This operation divides one number by another.
   - Example: `20 / 4 = 5`

5. **Exponentiation (^ or **)**: This operation raises one number to the power of another.
   - Example: `2^3 = 8` or `2**3 = 8`

## Combined Operations

Arithmetic expressions can combine multiple operations, and the order of operations (PEMDAS/BODMAS) is important to get the correct result:
- **Parentheses/Brackets**
- **Exponents/Orders**
- **Multiplication and Division**
- **Addition and Subtraction**

Examples:
- `3 + 2 * 5 = 13` (Multiplication before addition)
- `(3 + 2) * 5 = 25` (Parentheses first)
- `4^2 / 2 = 8` (Exponentiation before division)

In [6]:
# This is a simple arithmetic expression to multiply then add integers
(3*4)+5

17

In [7]:
# This will convert 200 minutes to hours by dividing by 60
200//60

3

**Objectives**
- Expand knowledge and skills in Data Science field

**AUTHOR**

Nam Danh Doan

In [2]:
class Vehicle:
    color = 'white'

In [4]:
V1 = Vehicle()
V1.color

'white'

In [10]:
import numpy as np
a = np.array([[1,0], [0,1]])
b = np.array([[2,2], [2,2]])
np.dot(a,b)

array([[2, 2],
       [2, 2]])

In [9]:
z

array([[1, 1],
       [1, 1]])